// @ts-check

// 此代码运行在 Node.js 环境中 - 不要在此处使用客户端代码（浏览器 APIs、JSX...）

/**
 * 创建侧边栏可以让您：
 - 创建有序的文档组
 - 为每个文档组渲染一个侧边栏
 - 提供上一页/下一页导航

 侧边栏可以从文件系统自动生成，也可以在此处明确定义。

 您可以创建任意数量的侧边栏。

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 默认情况下，Docusaurus 从 docs 文件夹结构生成侧边栏
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 但您也可以手动创建侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: '教程',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '农屿APP',
      items: [
        'nongyu-intro',
        'nongyu-features', 
        'nongyu-manual',
      ],
    },
  ],

};





export default sidebars;
